### ISSUE TITLE
Docs should note that :defined is not supported

### ISSUE THREAD

**Issue by arthurevans** [webcomponents/custom-elements#110]
May be obvious to some, but was not to me. For native custom elements, can use the `:defined` pseudo-class to style elements that have been defined (and probably more importantly, `:not(:defined)` to style elements that haven't been).

Current fix I believe is to manually add and remove an "unresolved" attribute, or equivalent.

**Comment by valdrinkoshi** [comment]
for completeness, the `unresolved` trick won't work for those elements that get upgraded lazily (e.g. after some user action). The `unresolved` attribute styling is done in `webcomponentsjs`, and the attribute is removed after at `WebComponentsReady` event.

**Comment by notwaldorf** [comment]
I think Arthur meant literally removing it manually, in the importHref callback, like how Shop does it.

**Comment by snuggs** [comment]
Salut! @notwaldorf @valdrinkoshi @arthurevans well done on documenting `:defined`. We are currently working through some inconsistencies between W3C/CSSOM/WHATWG in regards to `:defined` and it's pseudo-class definitions. You can follow this issue here https://github.com/w3c/webcomponents/issues/665

Just a heads up. Happy Sunday!
