### ISSUE TITLE
Edge Script Error: "Function Expected"

### ISSUE THREAD

**Issue by jtibble** [webcomponents/custom-elements#125]
Bringing in custom-elements.min.js to Edge throws a script error.

The line in question is https://github.com/webcomponents/custom-elements/blob/master/src/CustomElementInternals.js#L274  which compiles down to 

`
                    catch (m) {
                        throw a.__CE_state = 2, m;
                    }
`

which Edge throws a script error on saying "SCRIPT5002: Function expected". Can you take a look at the project compilation and see if there's a way to correctly compile this for Edge?

**Comment by TimvdLippe** [comment]
I am unable to reproduce this issue in Edge with this JSBin: http://jsbin.com/ceniwetero/edit?html,console,output @jtibble could you please supply a JSBin that shows the issue? You can take mine as a simple starting point

**Comment by bicknellr** [comment]
@jtibble, sorry about the delay, you're seeing this because some code below your element's constructor threw that error, which is caught and immediately thrown again after marking the element as having failed to upgrade. If you enable breaking on caught exceptions in the debugger, you should have an easier time finding the root cause.
