### ISSUE TITLE
`setAttribute` converts all attribute names to lowercase before setting

### ISSUE THREAD

**Issue by bicknellr** [webcomponents/custom-elements#14]
https://github.com/webcomponents/custom-elements/blob/a0f55ecbb17eee97aab877cfda9ac3a16b3b14ac/src/custom-elements.js#L768

In SVG, there are a lot of case-sensitive attribute names without namespaces. However, because `setAttribute` converts them to lowercase, it fails silently and ends up setting the wrong attribute. Not to mention, this is pretty hard to notice even inspecting since the only difference is the capitalization of certain letters or if (like me) you don't have a lot of experience with SVG.

This is easy to work around though: `element.setAttributeNS(null, 'caseSensitiveName', value)`.

Also, there doesn't seem to be a wrapper for `setAttributeNS` and other `NS`-suffixed functions. Is this intended?

**Comment by aaronshaf** [comment]
This bit me today with SVG's viewBox :-(

**Comment by aaronshaf** [comment]
This basically makes SVG unusable in some browsers in custom elements.

**Comment by chiefcll** [comment]
I was looking into this as well - I don't see why setAttribute is being patched as the mutation observer is handling the changing of attributes. 

Seems like this can be fixed by removing:
https://github.com/webcomponents/custom-elements/blob/36451e1dbe4e3b77d98499fc12132573d91d4a8b/src/custom-elements.js#L759-L785

I have and everything still works in FF + Safari 10 - need to check IE11

**Comment by bicknellr** [comment]
This should be fixed (v1.0.0-alpha.4): http://jsbin.com/yayibu/edit?html,output

**Comment by bicknellr** [comment]
BTW, this is were the new patches to attribute methods of the Element prototype start:
https://github.com/webcomponents/custom-elements/blob/f4b6f1f11e59012f7623236bb5ec8553b756940d/src/Patch/Element.js#L119
