### ISSUE TITLE
Error compiling m-datepicker

### ISSUE THREAD

**Issue by BarboraBardunova** [webcomponents/custom-elements#173]
when importing datepicker molecule like following:

`import AXADatepicker from '@axa-ch/patterns-library/lib/components/m-datepicker';`
`import withReact from '@axa-ch/patterns-library/lib/js/with-react';`

`const AXADatepickerReact = withReact(AXADatepicker);`

and inside of render() function:

`return <AXADatepickerReact value="" classes="o-datepicker js-datepicker" locale="de-ch"/>`

throws this error:
TypeError: _this2.offResize is not a function
at Datepicker.unListenToDeviceStateChange (device-state.js:67)
    at Datepicker.offListenToDeviceStateChange (index.js:206)
    at Datepicker.listenToDeviceStateChange (index.js:187)
    at Datepicker.init (index.js:180)...

**Comment by TimvdLippe** [comment]
Thanks for the issue. It has been a great while since this issue was opened. Sadly, this issue misses a live reproduction with the most recent version of the webcomponents polyfill for us to be able to debug and potentially fix. Versions 1 of the polyfills fix a large amount of issues, probably including this one as well.

Please see [the CONTRIBUTING.md](https://github.com/webcomponents/webcomponentsjs/blob/master/CONTRIBUTING.md) for guidelines on filing issues.  You can start from [this jsBin template](http://jsbin.com/birajez/edit?html,console,output) as a starting point and link it in the issue template under "Live Demo".

Feel free to file a new issue following these instructions if you can still reproduce this issue with versions 1 of the polyfills.  Thank you!
