### ISSUE TITLE
constructor that populates shadowRoot throws in STP if polyfill is loaded

### ISSUE THREAD

**Issue by JanMiksovsky** [webcomponents/custom-elements#18]
Repro: http://jsbin.com/jusodew/edit?html,output.
- This works in Canary, Firefox, and STP with Custom Elements turned off.
- This fails in STP with Custom Elements turned on, throwing `NotSupportedError (DOM Exception 9): A newly constructed custom element must not have child nodes`. If the polyfill is removed, it works as expected. That seems odd: if native CE is available, the polyfill should stay out of the way, no?

If this looks like a WebKit bug, let me know and I can file one for it.

**Comment by SerkanSipahi** [comment]
@JanMiksovsky What is STP? what you mean with "native CE".

**Comment by JanMiksovsky** [comment]
STP = Safari Technology Preview
CE = Custom Elements

**Comment by SerkanSipahi** [comment]
@JanMiksovsky thank you

**Comment by bicknellr** [comment]
Here's my guess. Native custom elements are specced to enforce [this set of restrictions on their constructors](https://html.spec.whatwg.org/#custom-element-conformance). ShadyDOM implements shadow trees by rendering the composed tree. If you're using both native shadow DOM and custom elements, the constructor in [your repro](http://jsbin.com/jusodew/edit?html,output) is totally fine because attaching a shadow tree and adding things to it is not prohibited by the constructor restrictions. However, if you're using ShadyDOM, when you attach a shadow tree and insert something into it, those inserted nodes end up as non-shadow descendants of the element being constructed. Then, when your constructor returns, the native custom elements implementation notices them and throws.

This is all assuming that when you said "If the polyfill is removed, it works as expected." you were referring to everything from 'webcomponents-lite.js' and not just the custom elements polyfill and that ShadyDOM was unconditional at the time.

**Comment by JanMiksovsky** [comment]
It looks like this may be fixed now.
