### ISSUE TITLE
[question] getting CustomElements to work in a webpack pipeline for older browsers

### ISSUE THREAD

**Issue by tconroy** [webcomponents/custom-elements#90]
Hey there,
I'm having some trouble getting this polyfill + native-shim to work right across all devices.

Some background on my setup:
* Webpack2 + babel-6
* app is written in ES6, transpiling to ES5 
* imports a `node_module` written in ES2015, which creates `CustomElements` used in the app

So the relevant webpack dev config looks something like this:

```
const config = webpackMerge(baseConfig, {
  entry: [
    'webpack/hot/only-dev-server',
    '@webcomponents/custom-elements/src/native-shim',
    '@webcomponents/custom-elements',
    '<module that uses CustomElements>/dist/src/main',
    './src/client',
  ],
  output: {
    path: path.resolve(__dirname, './../dist/assets/'),
    filename: 'app.js',
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        options: {
          cacheDirectory: true,
        },
        include: [
          path.join(NODE_MODULES_DIR, '<module that uses CustomElements>'),
          path.join(__dirname, '../src'),
        ],
      },
    ],
  },
...
```

key take aways: 
* I need CustomElement poly loaded before `<module that uses CustomElements>`
* I need `<module that uses CustomElements>` loaded before my app soure
* `<module that uses CustomElements>` is ES6 so we're transpiling it ( thus the include in the `babel-loader`).

The above works as-expected in modern ES6 browsers ( IE desktop Chrome ).

**HOWEVER**

I get the following error in older browsers, for example iOS 8:
```
SyntaxError: Unexpected token ')'
```

pointing to the opening anonymous function in the native-shim pollyfill:
```
(() => {
  'use strict';

  // Do nothing if `customElements` does not exist.
  if (!window.customElements) return;

  const NativeHTMLElement = window.HTMLElement;
  const nativeDefine = window.customElements.define;
  const nativeGet = window.customElements.get;
```

So it seems to me like the `native-shim` would need to be transpiled to ES5:

```
        include: [
+         path.join(NODE_MODULES_DIR, '@webcomponents/custom-elements/src/native-shim'),
          path.join(NODE_MODULES_DIR, '<module that uses CustomElements>'),
          path.join(__dirname, '../src'),
        ],
```

...but doing so now breaks both Chrome and iOS 8 with the following error:
```
app.js:1 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new StandInElement (native-shim.js:122)
    at HTMLDocument.createElement (<anonymous>:1:1545)
    at ReactDOMComponent.mountComponent (ReactDOMComponent.js:504)
    at Object.mountComponent (ReactReconciler.js:46)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:371)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
    at Object.updateChildren (ReactChildReconciler.js:121)
    at ReactDOMComponent._reconcilerUpdateChildren (ReactMultiChild.js:208)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:312)
```

.. which takes me to this `constructor()` line in the native-shim:
```
  window.customElements.define = (tagname, elementClass) => {
    const elementProto = elementClass.prototype;
    const StandInElement = class extends NativeHTMLElement {
      constructor() {
```

----

Phew. So it's very unclear to me how we actually include this in a webpack based build, where the dependency using CustomElements is ES6 ( and needs transpiling).

* Transpiling the native-shim to es5 doesn't work
* using the native-shim as-is at the top of the bundle entry point doesn't work for iOS 8, but does for Chrome
* not including the native-shim breaks both Chrome and iOS 

I'm really quite frustrated with web components at this point. I just want to use this one dependency that happens to be built with web components. How can I get it to work properly in a webpack build, and work across all devices? Am I missing something obvious here?

**My .babelrc config for posterity sake (dev config most relevant):**
```
{
  "presets": [
    ["es2015", { "modules": false }],
    "react"
  ],
  "plugins": [
    "transform-custom-element-classes",
    "transform-object-rest-spread",
    "transform-object-assign",
    "transform-exponentiation-operator"
  ],
  "env": {
    "test": {
      "plugins": [
        [ "babel-plugin-webpack-alias", { "config": "./cfg/test.js" } ]
      ]
    },
    "dev": {
      "plugins": [
        "react-hot-loader/babel",
        [ "babel-plugin-webpack-alias", { "config": "./cfg/dev.js" } ]
      ]
    },
    "dist": {
      "plugins": [
        [ "babel-plugin-webpack-alias", { "config": "./cfg/dist.js" } ],
        "transform-react-constant-elements",
        "transform-react-remove-prop-types",
        "minify-dead-code-elimination",
        "minify-constant-folding"
      ]
    },
    "production": {
      "plugins": [
        [ "babel-plugin-webpack-alias", { "config": "./cfg/server.js" } ],
        "transform-react-constant-elements",
        "transform-react-remove-prop-types",
        "minify-dead-code-elimination",
        "minify-constant-folding"
      ]
    }
  }
}

```

**Comment by bicknellr** [comment]
Hi @tconroy, the native shim can't be used compiled to ES5 because native custom elements implementations require that the `HTMLElement` constructor is called *as a constructor* from your code and only features available in ES2015 are able to do this.

Particularly, when using the native custom element implementation, your definition either...

- is written as a class extending `HTMLElement` and needs to call `super` in the constructor:

  ```js
  class MyElement extends HTMLElement {
    constructor() {
      super();
      // `this` is now the element.
      this.prop = 1234;
    }
  }
  customElements.define('my-element', MyElement);
  ```

- or, is written as a normal ES5 constructor and needs to call `Reflect.construct`, use its result instead of `this`, and return that result:

  ```js
  function MyElement() {
    // As usual, `this` does in fact exist here and it is an object
    // with `MyElement.prototype` as its prototype. However, there is
    // no way to call `HTMLElement` as a constructor while also
    // supplying the local `this` as the `this` value for the
    // construction.

    // To work around the above and because `super` has no meaning
    // within this function (or, more concretely, will cause a
    // SyntaxError), you must *construct* a new `HTMLElement`:
    var inst = Reflect.construct(HTMLElement, [], new.target);

    // Then, you can use the result as if it was `this`:
    inst.prop = 1234;

    // When plain functions are called as constructors and the function
    // returns undefined, the object that was automatically created to
    // become this (described in the first comment) is the result of
    // the construction. However, if the constructor returns an object
    // (primitives won't trigger this), that returned value is the
    // result of the construction:
    return inst;
  }
  MyElement.prototype = Object.create(HTMLElement.prototype);
  MyElement.prototype.constructor = MyElement;
  customElements.define('my-element', MyElement);
  ```

This ultimately means that if you give the native shim to a compiler to convert to ES5, the compiler will see the class and rewrite it in a way that it thinks is roughly equivalent - usually as a plain function with `HTMLElement.call(this)` acting as `super()`. However, because `HTMLElement` can only be called as a constructor in one of the ways above, anything in pure ES5 that the compiler converts it to isn't sufficient.

The native shim is only meant to wrap a native implementation of custom elements so that custom element definitions that have specifically been compiled from ES2015 to ES5 will work there. Particularly, it will break if you try to run it in a client that doesn't have a native custom elements implementation because `HTMLElement` won't be constructible. Also, because of how the native shim works right now, it doesn't work with ES2015 classes as custom element definitions - all definitions have to be compiled when using it. We'll look into it in the future but supporting mixed compilation situations doesn't seem to be that critical at the moment.

So, what do you actually need to do?
- If you decide to build (you're shipping ES5 definitions):
  - If the client you're running on has a native implementation of custom elements, you need to load the native shim.
  - Otherwise, you need to load the polyfill.
- If you decide not to build (you're shipping ES2015 definitions):
  - If the client you're running on has a native implementation of custom elements, you don't need to do include anything else.
  - Otherwise, you need to load the polyfill.

Also, you should load the polyfill separately, rather than bundling it with your app, so that clients that don't need it don't download it. If you're planning on using the full set of web components polyfills, take a look at [the loader in webcomponentsjs](https://github.com/webcomponents/webcomponentsjs/#webcomponents-loaderjs); it checks what things are supported by the browser its running in and loads only the polyfills needed by that browser.

Here's a small example project that uses webpack and babel to compile custom elements written in ES2015 (with modules) to ES5 and load the native shim or polyfill as needed:

https://glitch.com/edit/#!/webpack-babel-custom-elements

(result: https://webpack-babel-custom-elements.glitch.me)

The `document.write('<!--')` thing in `index.html` looks pretty gnarly but it works reliably and we use it in [`polymer build`](https://github.com/Polymer/polymer-build/) to optionally load the native shim. I've tried out that example project in IE11, mobile Safari 9, and most auto-updating browsers and everything checks out. However, the polyfill doesn't support Safari 8 ([here are the browsers it does](https://github.com/webcomponents/webcomponentsjs/#browser-support)), so I can't say whether or not it will work there.

**Comment by bicknellr** [comment]
Sorry, I left out an important distinction: you can definitely call a function as a constructor in ES5 - `new` :) - but the key part is that you can't pass `new.target`, which you can with `Reflect.construct` and is implied with `super()`. (The HTML spec's description of [HTML element constructors](https://html.spec.whatwg.org/multipage/dom.html#html-element-constructors) has the details of why you need `new.target`.) Also, that example might seem a bit strange since the polyfill / native shim are pretty separate from the webpack / babel stuff going on. (.. and serving directly from `node_modules`, I was lazy.) The point is just that the native shim and polyfill should be loaded separately from your bundle if your server isn't deciding what clients get what bundles. One thing you might want to consider doing is minifying (but not compiling) the native shim, this is also something that webcomponentsjs does ([description](https://github.com/webcomponents/webcomponentsjs#custom-elements-es5-adapterjs), [minified native shim](https://github.com/webcomponents/webcomponentsjs/blob/master/custom-elements-es5-adapter.js)).

**Comment by bicknellr** [comment]
Hmm, looks like my example was a bit too janky and started creating this nested series of folders called 'built' - just updated it with a slightly more robust build process.

**Comment by treshugart** [comment]
@hotell would what you're doing in skatejs/web-components#48 help make this simpler for consumers?

**Comment by Hotell** [comment]
ofc, with new skatejs/web-components everything is handled for you and you save 35kB in worst case scenario

best case - browser with full support of WC ( if you're transpiling to es5, just es5-adapter will be loaded - 2kb )
worst case - IE11 - lazy loaded polyfills/es6 needed features -> savings 35kb against webcomponnets shims in this repo

you can try it right now
- skate starter with typescript https://github.com/Hotell/skate-starter
